### PR TITLE
Fixed handling of PerResolveLifetimeManager.

### PR DESCRIPTION
**Pull request by SzymonPobiega**

### CODE REVIEW

**Comment by SzymonPobiega** [comment]
@Particular/persistence-maintainers please review.

**Comment by DavidBoike** [comment]
Did you mean to ping a different maintainer group?

**Comment by HEskandari** [comment]
Looks good @SzymonPobiega. Could you fix the code inspection issue? it is failing with this:

```27: Class 'Root' can be made private```

I'll merge it in once fixed.

**Comment by SzymonPobiega** [comment]
@HEskandari should be good now.

**Comment by HEskandari** [comment]
@SzymonPobiega still not happy.

```Auto-property accessor is never used```

**Comment by SzymonPobiega** [comment]
OK, now it's green. Squashing.

**Pull request merged**
