### PR TITLE
PropertyInjectionBuilderStrategy executed for child and parent container

### PR DESCRIPTION
**Pull request by marinkobabic**
When child container does a resolve, the the build strategies of parent and child container are executed. Depending on the order and lifetime the property can contain the wrong injected instance. The second drawback is the performance.

### CODE REVIEW

**Comment by SzymonPobiega** [comment]
Do I understand correctly that now only the parent container would be used when trying to inject the properties?

**Comment by marinkobabic** [comment]
No. Unity uses the child container first and then the parent. This is handled using the LifeTime concept and works also properly with my workaround. In our case is the problem that when the child container was able to resolve, you do the resolve using parent container as well. The origina idea was to have the PropertyInjectionBuilderStrategy only one per container but the fact is that you have for the child container the one of the parent and the one of the child container. So Unity does a for loop to strategies.count and executes both PropertyInjectionBuilderStrategies. This causes bad side effects.

**Comment by SzymonPobiega** [comment]
So it prevents from setting the property multiple times, right? Looks good to me. Do you have ReSharper installed? If so, could you please clean the inspection errors and we'll be ready to pull this in. Thanks!

**Comment by marinkobabic** [comment]
I tried to change the whole concept and to use IPropertySelectorPolicy to achive what you did using the PropertyInjectionBuilderStrategy. Then I saw the following test

```c#
        public void Setter_dependencies_should_be_supported_when_resolving_interfaces()
        {
            using (var builder = TestContainerBuilder.ConstructBuilder())
            {
                builder.Configure(typeof(SomeClass), DependencyLifecycle.InstancePerCall);
                builder.RegisterSingleton(typeof(IWithSetterDependencies), new ClassWithSetterDependencies());

                var component = (ClassWithSetterDependencies)builder.Build(typeof(IWithSetterDependencies));
                Assert.NotNull(component.ConcreteDependency, "Concrete classed should be property injected");
                Assert.NotNull(component.InterfaceDependency, "Interfaces should be property injected");
                Assert.NotNull(component.concreteDependencyWithSetOnly, "Set only properties should be supported");
            }
        }

```

In this example the singleton instance is passed into the container. So why you want to set any property on a existing instance, makes no sense to me. The instance was never created by the container. If I would register a singleton type, then the instance would be created by the container and the properties should be set.

**Comment by SzymonPobiega** [comment]
That is unfortunately a legacy we need to live with. Other container adapters were implemented in such a way that even when you provide you're own instance, it does inject dependencies via properties while resolving.

**Comment by marinkobabic** [comment]
Is this going to be merged? We have still an issue and I would appreciate it if you would create a hotfix.

**Comment by SzymonPobiega** [comment]
It fails the acceptance tests. Not sure why, but some of the dependencies does not get injected. Can you run `NServiceBus.Unity.AcceptanceTests` on your machine and verify? The acceptance tests require that you install MSMQ on your machine.

**Comment by marinkobabic** [comment]
Locally are all the tests working properly. Have no idea which of them failed now and how to reproduce it locally?

Thanks Marinko

**Comment by SzymonPobiega** [comment]
@marinkobabic If you run the tests`NServiceBus.Unity.AcceptanceTests` project, there are 24 tests failing. I see that there is a problem with injecting something to the `ISendMessages` implementation causing a `NullReferenceException`.

**Comment by marinkobabic** [comment]
I have still no idea why the tests fail on the build server. The last change is a simple one and should work definitely. If you run them locally, what is the result.

**Comment by marinkobabic** [comment]
When can I expect a feedback? Locally all the tests are passed. If you want I will send you a video? Hope to hear from you.

**Comment by SzymonPobiega** [comment]
OK, I pulled the latest and everything is fine.

**Comment by SzymonPobiega** [comment]
Thanks!

**Comment by SzymonPobiega** [comment]
@marinkobabic I missed the PR was based on `master`. We need one based on `develop` because we follow gitflow. Would you like me to rebase it and merge or you want to do it yourself?

**Comment by marinkobabic** [comment]
Hi Szymon

Have done the rebase, hope like expected. Never did it before ☺

Thanks
Marinko

Von: Szymon Pobiega [mailto:notifications@github.com]
Gesendet: Dienstag, 16. Juni 2015 09:37
An: Particular/NServiceBus.Unity
Cc: Babic Marinko
Betreff: Re: [NServiceBus.Unity] PropertyInjectionBuilderStrategy executed for child and parent container (#18)


@marinkobabic<https://github.com/marinkobabic> I missed the PR was based on master. We need one based on develop because we follow gitflow. Would you like me to rebase it and merge or you want to do it yourself?

**Comment by SzymonPobiega** [comment]
OK, @marinkobabic I finally manage to release it. Thanks!

**Comment by marinkobabic** [comment]
Thanks a lot :-)

**Pull request merged**
